# Generated by Django 2.0.3 on 2018-10-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180926_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerapply',
            options={'ordering': ['id'], 'verbose_name': '报名信息', 'verbose_name_plural': '报名信息'},
        ),
        migrations.AddField(
            model_name='customerapply',
            name='comment',
            field=models.CharField(default='未发送', max_length=20),
        ),
    ]
