# Generated by Django 2.0.3 on 2019-01-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': '外部用户', 'verbose_name_plural': '外部用户'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
