# Generated by Django 2.0.3 on 2019-01-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='article',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='活动'),
            preserve_default=False,
        ),
    ]
